#!/usr/bin/env bash

if ! [[ -x /usr/bin/fio ]]; then
  echo "fio is not installed!" >&2
  exit 1
fi

# a fio alias for commonly used quick benchmarks
# https://unix.stackexchange.com/a/392091
fio --loops=5 --size=1000m --filename=fiocrystalbench.tmp   \
  --stonewall --ioengine=libaio --direct=1                  \
  --name=Seqread      --bs=1m   --rw=read                   \
  --name=Seqwrite     --bs=1m   --rw=write                  \
  --name=512Kread     --bs=512k --rw=randread               \
  --name=512Kwrite    --bs=512k --rw=randwrite              \
  --name=4kQD32read   --bs=4k   --rw=randread  --iodepth=32 \
  --name=4kQD32write  --bs=4k   --rw=randwrite --iodepth=32;
