#!/usr/bin/env bash

# reencrypt and wrap a file into an encrypted luks container by truncating file a little
luksify() {
  file=${1:?file required}; shift 1;
  (
    set -xe;
    truncate -s +8M "${file}";
    cryptsetup -yq reencrypt --encrypt --type luks2 --resilience none --disable-locks --reduce-device-size 8M "$@" "${file}";
    truncate -s -4M "${file}";
  );
}

luksify "$@"
