#!/usr/bin/env bash

if ! command -v qpdf >/dev/null; then
  echo >&2 "pdfcat requires qpdf to be installed"
  exit 1
fi

# concatenate files with qpdf
pdfcat() {
  if [[ -t 1 ]]; then
    echo "err: refusing to write to terminal" >&2
    return 1
  fi
  qpdf --empty --pages "$@" -- -
}
pdfcat "$@"
