#!/usr/bin/env bash

if ! command -v gs >/dev/null; then
  echo >&2 "pdfmini requires gs (ghostscript) to be installed"
  exit 1
fi

# try to make a pdf smaller by recompressing images etc.
pdfsmaller() {
  if [[ $1 == -h ]] || [[ -z $1 ]] || [[ -z $2 ]]; then
    echo "usage: $ pdfsmaller <input.pdf> <output.pdf> [setting]" >&2
    echo " where setting can be: screen, *ebook, printer, prepress" >&2
    return 1
  fi
  gs -sDEVICE=pdfwrite \
    -dPDFSETTINGS="/${3:-ebook}" -q \
    -o "$2" "$1";
}
pdfsmaller "$@"
