#!/usr/bin/env bash

# read markdown files
if command -v glow >/dev/null; then

  markman() { glow --pager "${1-README.md}"; }

elif command -v pandoc >/dev/null; then

  markman() {
    file="${1-README.md}"
    pandoc -s -f markdown -t man "$file" \
      -M header="$(basename "$file")" \
      -M footer="$(readlink -f "$file")" \
    | man -l -
  }

else
  echo >&2 "neither pandoc nor github.com/charmbracelet/glow installed!"
  exit 1
fi

markman "$@"
