#!/usr/bin/env bash

# resize images with imagemagick in-place
imageres() {

  usage() { cat <<USAGE
usage: imageres [-i] [-s 40%] filename [output]
  -i       : convert in-place and overwrite original file
  -b       : add --gaussian-blur 0.05
  -q 85%   : specify quality factor
  -s 40%   : scaling factor, use any number or size accepted by -resize
  filename : input file
  output   : output file (when not using in-place)
USAGE
}

  # defaults
  local res="40%"
  local inplace="false"
  local gauss="false"
  local quality="85%"
  local input output

  # commandline parser
  local opt OPTIND
  while getopts "hibs:q:" opt; do
    local arg="${OPTARG}"
    case "${opt}" in

      h)  usage; return 0;;      # help
      \?) usage >&2; return 1;;  # invalid
      :)  usage >&2; return 1;;  # missing arg
      i)  inplace="true";;       # opt: in-place
      b)  gauss="true";;         # opt: gaussian blur
      q)  quality="${arg}";;     # opt: quality
      s)  res="${arg}";;         # opt: resize

    esac
  done
  shift $((OPTIND - 1))

  # input file required
  if [[ -z ${1+undefined} ]]; then
    echo "err: input file required" >&2
    usage; return 1;
  else
    input="${1}"
  fi

  # output file required if not in-place
  if [[ $inplace == true ]]; then
    output="${input}"
  else
    if [[ -z ${2+undefined} ]]; then
      echo "err: output file required" >&2
      usage; return 1;
    else
      output="${2}"
    fi
  fi

  # run command
  # shellcheck disable=SC2046
  magick "${input}" -strip -interlace Plane \
    $([[ $gauss == true ]] && printf '%s ' -gaussian-blur 0.05) \
    -resize "${res}" -quality "${quality}" \
    "${output}";

}

imageres "$@"
