#!/usr/bin/env bash

original="${1:?input filename required}";

prompt=$'\e[2mEnter filename: \e[0m'
if command -v gum >/dev/null; then
  newname=$(gum input --no-show-help --value "$(basename "$original")" --prompt "$prompt") \
  && mv -i -v "$original" "$(dirname "$original")/$newname"
else
  read -ei "$(basename "$original")" -p "$prompt" newname \
  && mv -i -v "$original" "$(dirname "$original")/$newname"
fi
