#!/usr/bin/env bash

# check for duplicate files by calculating checksum and printing duplicates
shadupes() {
  if [[ -n $1 ]]; then files=("$@"); else files=(*); fi
  echo "checking ${#files[@]} files with $(du -shc "${files[@]}" | tail -1) .."
  sha256sum "${files[@]}" | sort | uniq -w64 --all-repeated=prepend | cut -b 67-;
}
shadupes "$@"
