#!/usr/bin/env bash

if ! command -v smartctl >/dev/null; then
  echo "smartctl is required for this command" >&2
  exit 1
fi

smarthealth() {

  # one argument with block device is required
  if [[ -z ${1+defined} ]] || ! [[ -b $1 ]]; then
    echo "err: at least one argument with block device required" >&2
    echo "err: for example, 'smarthealth /dev/sda'" >&2
    return 1
  fi

  for disk in "$@"; do

    # print brief info and a selection of health stats
    printf '\033[1;33m----- SMART data for %s -----\033[0m\n' "$disk"
    if ! [[ -b $disk ]]; then
      echo "err: not a block device" >&2
      continue
    fi
    smartctl -H -l selftest -A -f brief "$disk" |\
      awk '{ if ($1 ~ /[0-9]+/) { if ($1 ~ /^(5|9|197|198)$/) { print $0 }} else { print $0 }}'

  done

}
smarthealth "$@"
