#!/usr/bin/env bash

# rankmirrors is included in the pacman-contrib package
if ! [[ -x /usr/bin/rankmirrors ]]; then
  echo "rankmirrors is not installed!" >&2
  exit 1
fi

set -e
say() { printf '%s\n' "$*" >&2; };

# https://wiki.archlinux.org/index.php/Mirrors#Fetching_and_ranking_a_live_mirror_list
say "fetch updated mirrorlist: DE/https/status=on ..."
mirrors=$(curl -sL "https://archlinux.org/mirrorlist/?country=DE&protocol=https&use_mirror_status=on" |\
  sed -e 's/^#Server/Server/' -e '/^#/d')

say "rank mirrors ..."
ranked=$(rankmirrors -n 10 - <<<"$mirrors")

list="/etc/pacman.d/mirrorlist"
say "replace $list ..."
printf "# ranked on %s\n%s\n" "$(date)" "$ranked" | sudo tee "$list"
