#!/usr/bin/env bash
# get public ip address information with wtfismyip.com
wtfismyip() {
  for type in ipv4 ipv6; do
    echo "$type:"
    local json
    json=$(curl -s "https://$type.wtfismyip.com/json")
    [[ -z $json ]] && { echo "  err: no $type connectivity?"; continue; }
    sed -n \
      -e 's/.*"YourFuckingIPAddress": "\(.*\)",.*/  address: \1/p' \
      -e 's/.*"YourFuckingHostname": "\(.*\)",.*/  hostname: \1/p' \
      <<<"$json";
  done
}
wtfismyip "$@"
