# bashrc file for interactive bash(1) shells.

# If not running interactively, don't do anything
[[ $- != *i* ]] && return;

# get real directory of this file (follow symlinks)
BASH_DOTFILES="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )"

# load configuration and aliases
for d in 'conf.d' 'aliases.d'; do
  
  confd="$BASH_DOTFILES/$d";

  if [[ -d $confd ]]; then
    for file in "$confd"/*; do
      source "$file";
    done
  else
    echo "${BASH_SOURCE[0]}: missing configuration directory at $confd" >&2
  fi

done
unset d confd

# load user aliases
[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases;
